szDjango/home/urls.py
from django.urls import path

from home.views import index, baidu, info, if_view, for_view, url_view, book_view, filter_view, static_view, re_view

# 指定应用名称
app_name = 'home'

urlpatterns = [
    path('', index, name='index'),
    path('baidu', baidu, name='baidu'),
    path('info', info, name='info'),
    path('if', if_view, name='if'),
    path('for', for_view, name='for'),
    path('url', url_view, name='url'),
    path('book/<book_id>',book_view, name='book'),
    path('filter',filter_view, name='filter'),
    path('sta',static_view,name='static'),
    path('wz',re_view,name='wz')
]

szDjango/movie/urls.py
from django.urls import path

from movie.views import movie_list, movie_detail

# 指定应用名称
app_name = 'movie'




urlpatterns = [
    path('list',movie_list, name='movie_list'),
    path('detail/<int:movie_id>',movie_detail)
]

szDjango/szDjango/urls.py
from django.contrib import admin
from django.urls import path, include, reverse
from django.shortcuts import HttpResponse
from book.views import book_detail, book_list, book_str, book_slug, book_path
from django.conf import settings
from django.conf.urls.static import static
# url与视图映射
# s/(url) --->视图函数 进行映射
# 视图函数
# def index(request):
#     print(reverse("movie:movie_list"))
#     # print(reverse("book_detail"))
#     # reverse("book_path",kwargs={"book_id":1})
#     return HttpResponse("欢迎你刚回来")


urlpatterns = [
    path('admin/', admin.site.urls),
    # path('', index, name='index'),
    path('book', book_detail, name='book_detail'),
    #     http://127.0.0.1:8000/book/1,指定参数类型，会出现404，在视图函数中得到就是整型，就则默认就是str
    path('book/<int:book_id>', book_list),
    path('book/str/<int:book_id>', book_str),
    path('book/slug/<slug:book_id>', book_slug),
    path('book/path/<path:book_id>', book_path, name='book_path'),

    path('movie/', include('movie.urls')),
    path('home/', include('home.urls')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

szDjango/book/models.py
from django.db import models

# Create your models here.

szDjango/home/models.py
from django.db import models

# Create your models here.

szDjango/movie/models.py
from django.db import models

# Create your models here.

szDjango/book/views.py
from django.shortcuts import render
from django.http import HttpResponse

# Create your views here.
'''
在url中携带参数
1.通过查询字符串(query string): https//www.baidu.com/s?
2.在path中携带：http://127.0.0.1:8000/book/2

'''


def book_detail(request):
    # request.GET={"id":3}
    request.GET.get('id')  # 没有会返回none
    book_id = request.GET.get('id')
    name = request.GET.get('name')

    return HttpResponse(f"你查找的图书id是:{book_id},图书名字是:{name}")


def book_list(request, book_id):
    return HttpResponse(f"你查找色图书是:{book_id}")


def book_str(request, book_id):
    return HttpResponse(f"图是是:{book_id}")

# 空格 下划线
def book_slug(request, book_id):
    return HttpResponse(f"图书是:{book_id}")


# 可以传/
def book_path(request, book_id):
    return HttpResponse(f"图书是:{book_id}")

szDjango/home/views.py
from django.shortcuts import render, HttpResponse


# Create your views here.
def index(request):
    return render(request, 'index.html')


def baidu(request):
    return render(request, 'baidu.html')


def info(request):
    # 1.普通的变量
    username = '你叫啥名字'
    # 2.字典类型
    book = {'name': "水浒传", 'auther': "施耐庵"}
    # 3.列表
    books = [
        {'name': "水浒传", 'auther': "施耐庵"},
        {'name': "三国演义", 'auther': "罗贯中"}
    ]

    # 4.对象
    class Person:
        def __init__(self, realname):
            self.realname = realname

    context = {
        'username': username,
        'book': book,
        'books': books,
        'person': Person('治疗课堂')

    }
    return render(request, 'info.html', context=context)


def if_view(request):
    age = 90
    return render(request, 'if.html', context={'age': age})


def for_view(request):
    # 列表
    books = [
        {'name': "水浒传", 'auther': "施耐庵"},
        {'name': "三国演义", 'auther': "罗贯中"}
    ]
    # 字典
    person = {'realname': "治疗课堂", 'age': 19, 'height': 190}

    context = {'books': books, 'person': person}

    return render(request, 'for.html', context=context)


def url_view(request):
    return render(request, 'url.html')


def book_view(request, book_id):
    return HttpResponse(f"你访问的图书id是:{book_id}")

def filter_view(request):
    greet="Hello World,   rdtyuijokgfhjklh uioygihu"
    from datetime import datetime
    context = {'greet': greet,'birthday': datetime.now()}
    return render(request,'filter.html',
                  context=context)


def static_view(request):
    return render(request, 'static.html')

def re_view(request):
    context={
        'articles':['小米su7','chatgpt']
    }
    return render(request, 'wz.html', context=context)

szDjango/movie/views.py
from django.shortcuts import render,HttpResponse

# Create your views here.
def movie_list(request):
    return HttpResponse("电影列表")


def movie_detail(request,movie_id):
    return HttpResponse(f"你的电影id:{movie_id}")

szDjango/home/templates/baidu.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>百度</title>
</head>
<body>
<h1 style="background-color: aquamarine">欢迎回来百度</h1>
</body>
</html>

szDjango/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %}--小饭桌</title>
{% block head %}{% endblock %}
</head>
<body>
<header>
    <ul>
        <li><a href="/">首页</a></li>
        <li><a href="/home/if">川谷额课堂</a></li>
    </ul>
</header>
{% block body %}我是来自父模板的{% endblock %}

<footer>版权信息</footer>
</body>
</html>

szDjango/templates/filter.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>过滤器使用</title>
</head>
<body>
<p>{{ greet|cut:"o" }}</p>
<p>生日：{{ birthday|date:"Y/m/d" }}</p>

</body>
</html>

szDjango/templates/for.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>for语句</title>
</head>
<body>
<table>
    <thead>
    <tr>
        <th>序号</th>
        <th>名称</th>
        <th>作者</th>
    </tr>
    </thead>


    <tbody>
    {% for book in books %}
        <tr>
            <td>{{ forloop.counter0 }}</td>
            <td>{{ book.name }}</td>
            <td>{{ book.auther }}</td>
        </tr>
        {% empty %}
        <tr>没有任何图书</tr>
    {% endfor %}
    </tbody>
</table>
<div>
    {% for key ,value in person.items %}
        <p> {{ key }}:{{ value }}</p>
    
    {% endfor %}
</div>



</body>
</html>

szDjango/templates/if.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>if标签</title>
</head>
<body>
{% if age > 18 %}
    <p>您已满18岁可以进入</p>
{% elif age == 18 %}
     <p> 需要观察</p>   
{% else %}
    <p>不可以进入</p>

{% endif %}
</body>
</html>

szDjango/templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>这是我的课件</title>
</head>
<body>
    <h1 style="background-color: antiquewhite">欢迎回来</h1>
</body>
</html>

szDjango/templates/info.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>信心</title>
</head>
<body>
<p style="background-color: aqua">{{ username }}</p>
<p>图书名称:{{ book.name }}</p>
<p>下标为一的图书名称:{{ books.0.name }}</p>
<p>姓名为:{{ person.realname }}</p>
</body>
</html>

szDjango/templates/rmwz.html
<div>
    <h2>热门文章</h2>
    <ul>
        {% for article in articles %}
        <li>{{ article }}</li>
        {% endfor %}
    </ul>
</div>

szDjango/templates/static.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>静态文件加载</title> 
    <link rel="stylesheet" href="{% static 'css/index.css'%}">
    <script src="{% static 'js/index.js' %}"></script>
</head>
<body>
<h1>我的课堂</h1>
</body>
</html>

szDjango/templates/url.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>url标题</title>
</head>
<body>
<a href="{% url 'home:if' %}">百度</a>
<a href="{% url 'home:book' 1 %}">图书详情</a>
</body>
</html>

szDjango/templates/wz.html
{% extends 'base.html' %}

{% block title %}
	首页
{% endblock %}





{% block head %}
	<style>
    body{
        background-color: aqua;
    }
    </style>
{% endblock %}





{% block body %}
    {{ block.super }}
	{%  include 'rmwz.html' %}
    <div> ertyuio</div>
{% endblock %}